### ISSUE TITLE
404 error 

### ISSUE THREAD

**Issue by pspmiracle** [Cleod9/SpriteSatchel#2]
I tried to download air package here - http://www.mcleodgaming.com/downloads/SpriteSatchel.0.5.9.air But I got 404 error. Please fix this link.
<img width="762" alt="screen shot 2015-07-06 at 12 21 11" src="https://cloud.githubusercontent.com/assets/4035827/8519192/883fb4c2-23d9-11e5-8bcf-15d05bf97e83.png">

Thanks!

**Comment by Cleod9** [comment]
Thanks a ton for the error report! I recently had a server crash and had to restore everything, guess I forgot to re-upload. I'll take care of it right away when i get home tonight

**Comment by Cleod9** [comment]
@pspmiracle all done re-uploading! thanks again for reporting
